# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#a4e3d3"
background = "#111014"
dim_foreground = "#99b7af"
bright_foreground = "#9ec5cc"

[colors.cursor]
text = "#ffffff"
cursor = "#a4e3d3"

[colors.vi_mode_cursor]
text = "#a4e3d3"
cursor = "#a4e3d3"

[colors.search.matches]
foreground = "#a4e3d3"
background = "#a4e3d3"

[colors.search.focused_match]
foreground = "#a4e3d3"
background = "#1a1123"

[colors.hints.start]
foreground = "#a4e3d3"
background = "#1a1123"

[colors.hints.end]
foreground = "#a4e3d3"
background = "#1a1123"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#a4e3d3"
background = "#1a1123"

[colors.selection]
text = "#a4e3d3"
background = "#ffffff"

[colors.normal]
black = "#1a1123"
red = "#f4215c"
green = "#398f31"
yellow = "#f6e977"
blue = "#a4e3d3"
magenta = "#b821f4"
cyan = "#639b96"
white = "#ffffff"

[colors.bright]
black = "#1a1123"
red = "#f4215c"
green = "#398f31"
yellow = "#f6e977"
blue = "#a4e3d3"
magenta = "#b821f4"
cyan = "#21d4f4"
white = "#ffffff"

[colors.dim]
black = "#1a1123"
red = "#f4215c"
green = "#398f31"
yellow = "#f6e977"
blue = "#a4e3d3"
magenta = "#b821f4"
cyan = "#639b96"
white = "#ffffff"
