[colors.primary]
background = '#191113'
foreground = '#efdfe1'

[colors.selection]
text = '#efdfe1'
background = '#6f3349'

[colors.cursor]
text = '#191113'
cursor = '#ffb0c9'

[colors.normal]
black   = '#191113'
red     = '#d25e38'
green   = '#6ed686'
yellow  = '#cddb7b'
blue    = '#cd5b7f'
magenta = '#bf8f9e'
cyan    = '#ffb0c9'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e07f5f'
green   = '#86e09a'
yellow  = '#dce897'
blue    = '#ffbcd7'
magenta = '#b85a87'
cyan    = '#ae6372'
white   = '#ffffff'
